spring:
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
  data:
    mongodb:
      port: 27017
      database: library
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://localhost:5432/library
    user: postgres